**Numpy library**

In [1]:
print('hello')

hello


In [2]:
a = 2
a

2

In [3]:
a = 2
b = 3
print('a = ' + str(a) + ' and ' + 'b = ' + str(b)) # convert int to str

a = 2 and b = 3


In [4]:
type(a) # check type of variable a

int

In [5]:
s1 = 'RJ college'
type(s1)

str

In [6]:
f=2.34546796547
type(f)

float

> indent


$y = x^2$

https://numpy.org/doc/stable/user/whatisnumpy.html

In [7]:
a=[1,2,3]
a

[1, 2, 3]

In [8]:
type(a)

list

In [9]:
b=[4,5,6]
b

[4, 5, 6]

In [10]:
c = []

for i in range(len(a)):
  c.append(a[i]*b[i])

print(c)

[4, 10, 18]


In [11]:
c = []

for i in range(len(a)):
  c.append(a[i]+b[i])

print(c)

[5, 7, 9]


In [12]:
import time
print('sleeping')

time.sleep(30)
print('done sleeping')

sleeping
done sleeping


## np.arange(a(start), n(end), s(step)) -> returns a to (n-1) with difference of s(step) between each value of a to (n-1)

## np.reshape(x, y) -> converts linear data to metric format (x(rows), y(columns))

In [13]:
import numpy as np

a=np.arange(15).reshape(3,5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## a.ndim -> no. of array dimension

In [14]:
a.ndim

2

In [15]:
a.dtype

dtype('int32')

In [16]:
a.dtype.name

'int32'

## itemsize -> size of each item in array in bytes; size -> size of array

In [17]:
a.itemsize

4

In [18]:
a.size

15

In [19]:
type(a)

numpy.ndarray

## np.array() -> creates array

In [20]:
b=np.array([[11,13,14],[56,57,58]])
b

array([[11, 13, 14],
       [56, 57, 58]])

In [21]:
b.reshape(3,2)
b

array([[11, 13, 14],
       [56, 57, 58]])

In [22]:
c=b.reshape(3,2)
c

array([[11, 13],
       [14, 56],
       [57, 58]])

In [23]:
d=np.array([['a','b','c','d','e'],['f','g','h','i','j']])
d

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')

In [24]:
e=d.reshape(2,5)
e

array([['a', 'b', 'c', 'd', 'e'],
       ['f', 'g', 'h', 'i', 'j']], dtype='<U1')